# Generated by Django 4.1.7 on 2023-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_system', '0002_remove_employee_is_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='full_name',
        ),
    ]
